language: php

sudo: false

services:
  - mysql
  - redis

matrix:
  include:
    - php: 5.4
      env: SYMFONY_VERSION='^2.8'
  fast_finish: true

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer config extra.symfony.require "$SYMFONY_VERSION"
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpunit
